### ISSUE TITLE
Using Flareresolverr docker image to bypass CF ? 

### ISSUE THREAD

**Issue by itanivalkyrie** [Esteban795/SushiscanScraper#4]
> Bypass cloudflare to allow people to have access to a bigger library. (i.e using sushiscan.net URLs instead of sushiscan.fr) (didn't manage a way around that. Tried cloudscraper, proxies, captcha solvers but nothing that was free worked. If you have any advices on that, I'll gladly add it to the program.)

Hello
Did you planned to add Flareresolverr support or use it ?

Thanks for your time and work.

**Comment by Esteban795** [comment]
Hello,
Flaresolverr didn't seem to be able to bypass cloudflare as I needed it to in the past : maybe it has changed though, and I'm willing to give it another try in the near future (probably during next week, as I won't be really busy). I'll keep you updated on that !
At the same time, if you have anything working with that, I'll be happy to collaborate with you on this project. 
Thanks for your input.

**Comment by Esteban795** [comment]
Hey, after trying again, I actually managed to make it work. I'll try and implement it for next week !

**Comment by Esteban795** [comment]
@toniohc 
After discussing with people on Flaresolverr's repo, it actually turns out it is NOT possible to implement due to not being able to *download* through Flaresolverr. I can always get the image's URL, but I can't save it locally, making the whole process useless. 

To detail a bit more : 
I'm creating my own [flaresolverr wrapper](https://github.com/Esteban795/flaresolverr-wrapper) in Python, but even using Flaresolverr `sessions` won't get me further : I need to make post request to the proxy server in order to bypass CF, but not using it with the exact same session in Flaresolverr make them invalid. And I can't download through Flaresolverr, as stated in [this issue I opened on the main repo](https://github.com/FlareSolverr/FlareSolverr/issues/1042).
